project:
  type: website
  resources:
    - assets/**        # copy everything under assets

format:
  revealjs:
    theme: [default, mpg.scss]
    logo: /assets/crest.png        # root-relative path is safest
    slide-number: true
    footer: "Max Planck Institute of Geoanthropology | YOUR NAME"
    transition: fade
    controls: true
    toc: false
    code-overflow: wrap
    width: 1920
    height: 1080
    margin: 0.02                   # no outer margin, good for full-bleed bgs
    template-partials:
      - title-slide.html
